AMD encoding support
Wieku/danser-go pull request #353
Opened 2023-12-27 17:11 UTC by vipotaenko02

Not sure if this will work perfectly but I will continue to contribute to this request. I know support for AMD hardware encoding was dropped, but at least knowing the risk in edge cases like low-end CPU this may help. And there is also an opened issue about AMD pro drivers on Linux, which may help encoding work better there (not sure though, for now I can only test Windows support, but eventually I'll get working on a Linux support too). For the time being, while support is experimental I will build a forked version with changes I made there. If anyone's interested, testing will be greatly helpful.

2023-12-27 17:33 UTC, vipotaenko02 commented
For now the tasks are:

- [ ] Rewrite ffmpeg download while building, because for now it downloads a version without needed encoders
- [ ] Add encoder options, such as profile, etc
- [ ] Thoroughly test encoder support to not be worse then software one
- [ ] Make Linux support through the same encoders (if possible) or through vaapi

2024-02-26 13:05 UTC, Wieku requested changes
Except for import sorting it looks ok. I can merge it as soon as more granular control for qp is added (qp_i, qp_b, qp_p flags ig?)

2024-09-24 02:11 UTC, xDololow commented
I have a mini-PC with 8845HS running Ubuntu Server, i can test amf and vaapi on that. Also what about av1 support?

2024-12-02 16:59 UTC, waylaa commented
> @vipotaenko02 What's the status of this?
> 
> BTW The newest release of https://github.com/Wieku/FFmpeg-Builds should now support amf, can you test it?

Perhaps you can take a look at #386 ?

2025-02-18 00:07 UTC, Wieku commented
Closing in favor of #386

2025-02-18 00:07 UTC, closed without merging